name: Generate Snake Animation

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Brijanshu07  # change to your GitHub username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
